/* ============================================================
   Shopify connection – GENERATED by scripts/shopify-sync.js on 2026-09-12.
   Re-run the script after changing designs or prices; edit only
   storefrontToken / apiVersion by hand.

   Mode A (checkout links, every plan): domain + products below.
   Mode B (Storefront API, Basic+):     additionally set storefrontToken.
   ============================================================ */
const SHOPIFY = {
  domain: '76u1ie-i3.myshopify.com',
  currency: 'EUR',

  /* Mode A: variant IDs per design slug (see cards.js) */
  products: {
    'dark-magician': [
      {variantId: '58700188647798', title: "Stand / Frame only", price: 49},
      {variantId: '58700229181814', title: "Stand / With display slab", price: 57},
      {variantId: '58700188680566', title: "Wall mount / Frame only", price: 49},
      {variantId: '58700229214582', title: "Wall mount / With display slab", price: 57},
    ],
    'blue-eyes': [
      {variantId: '58700189008246', title: "Stand / Frame only", price: 49},
      {variantId: '58700229247350', title: "Stand / With display slab", price: 57},
      {variantId: '58700189041014', title: "Wall mount / Frame only", price: 49},
      {variantId: '58700229280118', title: "Wall mount / With display slab", price: 57},
    ],
    'deep-eyes': [
      {variantId: '58700189073782', title: "Stand / Frame only", price: 49},
      {variantId: '58700229312886', title: "Stand / With display slab", price: 57},
      {variantId: '58700189106550', title: "Wall mount / Frame only", price: 49},
      {variantId: '58700229345654', title: "Wall mount / With display slab", price: 57},
    ],
    'kuriboh': [
      {variantId: '58700189139318', title: "Stand / Frame only", price: 49},
      {variantId: '58700229378422', title: "Stand / With display slab", price: 57},
      {variantId: '58700189172086', title: "Wall mount / Frame only", price: 49},
      {variantId: '58700229411190', title: "Wall mount / With display slab", price: 57},
    ],
    'dark-dragoon': [
      {variantId: '58700189204854', title: "Stand / Frame only", price: 49},
      {variantId: '58700229443958', title: "Stand / With display slab", price: 57},
      {variantId: '58700189237622', title: "Wall mount / Frame only", price: 49},
      {variantId: '58700229476726', title: "Wall mount / With display slab", price: 57},
    ],
    'black-chaos': [
      {variantId: '58700189303158', title: "Stand / Frame only", price: 49},
      {variantId: '58700229509494', title: "Stand / With display slab", price: 57},
      {variantId: '58700189335926', title: "Wall mount / Frame only", price: 49},
      {variantId: '58700229542262', title: "Wall mount / With display slab", price: 57},
    ],
    'black-luster': [
      {variantId: '58700189434230', title: "Stand / Frame only", price: 49},
      {variantId: '58700229575030', title: "Stand / With display slab", price: 57},
      {variantId: '58700189466998', title: "Wall mount / Frame only", price: 49},
      {variantId: '58700229607798', title: "Wall mount / With display slab", price: 57},
    ],
    'red-eyes-exceed': [
      {variantId: '58700189499766', title: "Stand / Frame only", price: 49},
      {variantId: '58700229640566', title: "Stand / With display slab", price: 57},
      {variantId: '58700189532534', title: "Wall mount / Frame only", price: 49},
      {variantId: '58700229673334', title: "Wall mount / With display slab", price: 57},
    ],
    'ra': [
      {variantId: '58700189630838', title: "Stand / Frame only", price: 49, available: false},
      {variantId: '58700229706102', title: "Stand / With display slab", price: 57, available: false},
      {variantId: '58700189663606', title: "Wall mount / Frame only", price: 49, available: false},
      {variantId: '58700229738870', title: "Wall mount / With display slab", price: 57, available: false},
    ],
    'flare-wingman': [
      {variantId: '58700189696374', title: "Stand / Frame only", price: 49},
      {variantId: '58700229804406', title: "Stand / With display slab", price: 57},
      {variantId: '58700189729142', title: "Wall mount / Frame only", price: 49},
      {variantId: '58700229837174', title: "Wall mount / With display slab", price: 57},
    ],
    'winged-kuriboh': [
      {variantId: '58700189761910', title: "Stand / Frame only", price: 49},
      {variantId: '58700229902710', title: "Stand / With display slab", price: 57},
      {variantId: '58700189794678', title: "Wall mount / Frame only", price: 49},
      {variantId: '58700229935478', title: "Wall mount / With display slab", price: 57},
    ],
    'cyber-end': [
      {variantId: '58700189827446', title: "Stand / Frame only", price: 49},
      {variantId: '58700229968246', title: "Stand / With display slab", price: 57},
      {variantId: '58700189860214', title: "Wall mount / Frame only", price: 49},
      {variantId: '58700230001014', title: "Wall mount / With display slab", price: 57},
    ],
    'stardust': [
      {variantId: '58700189892982', title: "Stand / Frame only", price: 49},
      {variantId: '58700228428150', title: "Stand / With display slab", price: 57},
      {variantId: '58700189925750', title: "Wall mount / Frame only", price: 49},
      {variantId: '58700228460918', title: "Wall mount / With display slab", price: 57},
    ],
    'shooting-quasar': [
      {variantId: '58700189958518', title: "Stand / Frame only", price: 49},
      {variantId: '58700230033782', title: "Stand / With display slab", price: 57},
      {variantId: '58700189991286', title: "Wall mount / Frame only", price: 49},
      {variantId: '58700230066550', title: "Wall mount / With display slab", price: 57},
    ],
    'crimson-dragon': [
      {variantId: '58700190024054', title: "Stand / Frame only", price: 49},
      {variantId: '58700230099318', title: "Stand / With display slab", price: 57},
      {variantId: '58700190056822', title: "Wall mount / Frame only", price: 49},
      {variantId: '58700230132086', title: "Wall mount / With display slab", price: 57},
    ],
    'red-nova': [
      {variantId: '58700190089590', title: "Stand / Frame only", price: 49},
      {variantId: '58700230361462', title: "Stand / With display slab", price: 57},
      {variantId: '58700190122358', title: "Wall mount / Frame only", price: 49},
      {variantId: '58700230394230', title: "Wall mount / With display slab", price: 57},
    ],
    'utopia': [
      {variantId: '58700190155126', title: "Stand / Frame only", price: 49},
      {variantId: '58700230426998', title: "Stand / With display slab", price: 57},
      {variantId: '58700190187894', title: "Wall mount / Frame only", price: 49},
      {variantId: '58700230459766', title: "Wall mount / With display slab", price: 57},
    ],
    'neo-galaxy-eyes': [
      {variantId: '58700190253430', title: "Stand / Frame only", price: 49},
      {variantId: '58700230492534', title: "Stand / With display slab", price: 57},
      {variantId: '58700190286198', title: "Wall mount / Frame only", price: 49},
      {variantId: '58700230525302', title: "Wall mount / With display slab", price: 57},
    ],
    'odd-eyes': [
      {variantId: '58700190351734', title: "Stand / Frame only", price: 49},
      {variantId: '58700230558070', title: "Stand / With display slab", price: 57},
      {variantId: '58700190384502', title: "Wall mount / Frame only", price: 49},
      {variantId: '58700230590838', title: "Wall mount / With display slab", price: 57},
    ],
    'starving-venom': [
      {variantId: '58700190417270', title: "Stand / Frame only", price: 49},
      {variantId: '58700230623606', title: "Stand / With display slab", price: 57},
      {variantId: '58700190450038', title: "Wall mount / Frame only", price: 49},
      {variantId: '58700230656374', title: "Wall mount / With display slab", price: 57},
    ],
    'clear-wing': [
      {variantId: '58700190482806', title: "Stand / Frame only", price: 49},
      {variantId: '58700230689142', title: "Stand / With display slab", price: 57},
      {variantId: '58700190515574', title: "Wall mount / Frame only", price: 49},
      {variantId: '58700230721910', title: "Wall mount / With display slab", price: 57},
    ],
    'dark-rebellion': [
      {variantId: '58700190548342', title: "Stand / Frame only", price: 49},
      {variantId: '58700230820214', title: "Stand / With display slab", price: 57},
      {variantId: '58700190581110', title: "Wall mount / Frame only", price: 49},
      {variantId: '58700230852982', title: "Wall mount / With display slab", price: 57},
    ],
    'decode-talker': [
      {variantId: '58700190613878', title: "Stand / Frame only", price: 49},
      {variantId: '58700231377270', title: "Stand / With display slab", price: 57},
      {variantId: '58700190646646', title: "Wall mount / Frame only", price: 49},
      {variantId: '58700231410038', title: "Wall mount / With display slab", price: 57},
    ],
    'firewall': [
      {variantId: '58700190679414', title: "Stand / Frame only", price: 49},
      {variantId: '58700231442806', title: "Stand / With display slab", price: 57},
      {variantId: '58700190712182', title: "Wall mount / Frame only", price: 49},
      {variantId: '58700231475574', title: "Wall mount / With display slab", price: 57},
    ],
    'borreload': [
      {variantId: '58700190744950', title: "Stand / Frame only", price: 49},
      {variantId: '58700231508342', title: "Stand / With display slab", price: 57},
      {variantId: '58700190777718', title: "Wall mount / Frame only", price: 49},
      {variantId: '58700231541110', title: "Wall mount / With display slab", price: 57},
    ],
  },

  /* Mode B */
  storefrontToken: '',
  apiVersion: '2026-04',
};
