/* ============================================================
   Shopify connection – GENERATED by scripts/shopify-sync.js on 2026-09-12.
   Re-run the script after changing designs or prices; edit only
   storefrontToken / apiVersion by hand.

   Mode A (checkout links, every plan): domain + products below.
   Mode B (Storefront API, Basic+):     additionally set storefrontToken.
   ============================================================ */
const SHOPIFY = {
  domain: '76u1ie-i3.myshopify.com',
  currency: 'EUR',

  /* Mode A: variant IDs per design slug (see cards.js) */
  products: {
    'dark-magician': [
      {variantId: '58700188647798', title: "Stand", price: 49},
      {variantId: '58700188680566', title: "Wall mount", price: 49},
    ],
    'blue-eyes': [
      {variantId: '58700189008246', title: "Stand", price: 49},
      {variantId: '58700189041014', title: "Wall mount", price: 49},
    ],
    'deep-eyes': [
      {variantId: '58700189073782', title: "Stand", price: 49},
      {variantId: '58700189106550', title: "Wall mount", price: 49},
    ],
    'kuriboh': [
      {variantId: '58700189139318', title: "Stand", price: 49},
      {variantId: '58700189172086', title: "Wall mount", price: 49},
    ],
    'dark-dragoon': [
      {variantId: '58700189204854', title: "Stand", price: 49},
      {variantId: '58700189237622', title: "Wall mount", price: 49},
    ],
    'black-chaos': [
      {variantId: '58700189303158', title: "Stand", price: 49},
      {variantId: '58700189335926', title: "Wall mount", price: 49},
    ],
    'black-luster': [
      {variantId: '58700189434230', title: "Stand", price: 49},
      {variantId: '58700189466998', title: "Wall mount", price: 49},
    ],
    'red-eyes-exceed': [
      {variantId: '58700189499766', title: "Stand", price: 49},
      {variantId: '58700189532534', title: "Wall mount", price: 49},
    ],
    'ra': [
      {variantId: '58700189630838', title: "Stand", price: 49, available: false},
      {variantId: '58700189663606', title: "Wall mount", price: 49, available: false},
    ],
    'flare-wingman': [
      {variantId: '58700189696374', title: "Stand", price: 49},
      {variantId: '58700189729142', title: "Wall mount", price: 49},
    ],
    'winged-kuriboh': [
      {variantId: '58700189761910', title: "Stand", price: 49},
      {variantId: '58700189794678', title: "Wall mount", price: 49},
    ],
    'cyber-end': [
      {variantId: '58700189827446', title: "Stand", price: 49},
      {variantId: '58700189860214', title: "Wall mount", price: 49},
    ],
    'stardust': [
      {variantId: '58700189892982', title: "Stand", price: 49},
      {variantId: '58700189925750', title: "Wall mount", price: 49},
    ],
    'shooting-quasar': [
      {variantId: '58700189958518', title: "Stand", price: 49},
      {variantId: '58700189991286', title: "Wall mount", price: 49},
    ],
    'crimson-dragon': [
      {variantId: '58700190024054', title: "Stand", price: 49},
      {variantId: '58700190056822', title: "Wall mount", price: 49},
    ],
    'red-nova': [
      {variantId: '58700190089590', title: "Stand", price: 49},
      {variantId: '58700190122358', title: "Wall mount", price: 49},
    ],
    'utopia': [
      {variantId: '58700190155126', title: "Stand", price: 49},
      {variantId: '58700190187894', title: "Wall mount", price: 49},
    ],
    'neo-galaxy-eyes': [
      {variantId: '58700190253430', title: "Stand", price: 49},
      {variantId: '58700190286198', title: "Wall mount", price: 49},
    ],
    'odd-eyes': [
      {variantId: '58700190351734', title: "Stand", price: 49},
      {variantId: '58700190384502', title: "Wall mount", price: 49},
    ],
    'starving-venom': [
      {variantId: '58700190417270', title: "Stand", price: 49},
      {variantId: '58700190450038', title: "Wall mount", price: 49},
    ],
    'clear-wing': [
      {variantId: '58700190482806', title: "Stand", price: 49},
      {variantId: '58700190515574', title: "Wall mount", price: 49},
    ],
    'dark-rebellion': [
      {variantId: '58700190548342', title: "Stand", price: 49},
      {variantId: '58700190581110', title: "Wall mount", price: 49},
    ],
    'decode-talker': [
      {variantId: '58700190613878', title: "Stand", price: 49},
      {variantId: '58700190646646', title: "Wall mount", price: 49},
    ],
    'firewall': [
      {variantId: '58700190679414', title: "Stand", price: 49},
      {variantId: '58700190712182', title: "Wall mount", price: 49},
    ],
    'borreload': [
      {variantId: '58700190744950', title: "Stand", price: 49},
      {variantId: '58700190777718', title: "Wall mount", price: 49},
    ],
  },

  /* Mode B */
  storefrontToken: '',
  apiVersion: '2026-04',
};
